### ISSUE TITLE
Consider adding "security"

### ISSUE THREAD

**Issue by zbentley** [flurdy/bad_usernames#1]
security@site.com is a common means of emailing a security team. A username of "security" could be used to impersonate that team, or capture emails directed to it if contact info was not available. Such emails could easily include sensitive information.

Because of this, I think "security" should be added to the list.

Thanks!

**Comment by flurdy** [comment]
Hi, 
"security" has been on the bad usernames list since day 1 :)

https://github.com/flurdy/bad_usernames/blob/master/bad_usernames.en.json#L50

**Comment by zbentley** [comment]
Turns out I was consuming the list wrong and that was my test value. Sorry,
and thanks again!
